/**
 * @param {type} <%= moduleName %> module
 * @author <%- author %>
 * @since <%= date %>
 */

(function() {
  define(['./<%= moduleName %>.module'], function(module) {
    'use strict';

    module.controller('<%= factoryName %>', <%= serviceName %>);

    <%= factoryName %>.$inject = ['$log'];

    function <%= factoryName %> ($log) {
      var factory = {};

      factory.method = method;

      function method() {
        // TODO autogenerated method stub...
      }

      return service;
    }
  });
})();
