/**
 * @param {type} <%= moduleName %> module
 * @author <%- author %>
 * @since <%= date %>
 */

(function () {
    define(['./<%= moduleName %>.module'], function (moduleName) {
        'use strict';

        angular.module(moduleName)
            .factory('<%= factoryName %>', <%= factoryName %>);

        <%= factoryName %>.$inject = ['$log'];

        function <%= factoryName %> ($log) {
            var factory = {};

            factory.method = method;

            function method() {
                // TODO autogenerated method stub...
            }

            return factory;
        }
    });
})();
